# Generated by Django 3.2.4 on 2021-06-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='marmalade',
            field=models.BooleanField(default=False),
        ),
    ]
