# Generated by Django 3.2.4 on 2021-06-21 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210621_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_friends_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
