# Generated by Django 3.2.4 on 2021-06-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_friends_friend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user', 'friend')},
        ),
    ]
